version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven dependencies...
      - mvn install -DskipTests
  build:
    commands:
      - echo Building the Maven project...
      - mvn package

artifacts:
  base-directory: backup/ec2-user/web-project/target
  files:
    - '*.jar'

